### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by rhys-vdw** [davglass/prettysize#13]
Is there a changelog available? I am wondering what breaking changes occurred between 0.1.0 and 1.0.0. Thanks!

**Comment by davglass** [comment]
I don't keep a changelog on this project, I just use the commit messages. Nothing much has changed since it was written in 2013 except that someone PR'd an upgrade to ES6 and added support for an `Object` as the second argument instead of all the parameters.

**Comment by rhys-vdw** [comment]
Our site went down for IE11 users because you're not compiling the ES6. 1.0.0 is broken and should probably be deprecated. Pls merge #9.
