### ISSUE TITLE
Feature request: ability to specify number of decimals

### ISSUE THREAD

**Issue by KeesCBakker** [davglass/prettysize#4]
I like to be able to specify the number of decimals of the result. Currently the module returns a result with a single decimal. I like to have 2 decimals.

**Comment by davglass** [comment]
I added this signature:

```js
var str = pretty(123456789, false, true, 2);
//str = "117.74 M"

var str = pretty(123456789, false, true, 3);
//str = "117.738 M"
```

Published in `prettysize@0.1.0`

**Comment by KeesCBakker** [comment]
Thanks man!

**Comment by crapthings** [comment]
what if i don't need decimals, it doesn't work if set "false" or 0
